import { describe, expect, test } from "bun:test"

import { createMemoryHost, runCli } from "../src/index"

const snapshot = {
  graphs: {
    mission_alpha: {
      mission: {
        id: "mission_alpha",
        goal: "Build Runesmith",
        status: "running",
        rootTaskId: "task_alpha",
        createdAt: "2026-05-27T00:00:00.000Z",
        updatedAt: "2026-05-27T00:00:00.000Z",
      },
      tasks: {
        task_alpha: {
          id: "task_alpha",
          missionId: "mission_alpha",
          title: "Mission root",
          description: "Build Runesmith",
          status: "running",
          requiredCapabilities: ["typescript"],
          assignedAgentId: "agent_atlas",
          createdAt: "2026-05-27T00:00:00.000Z",
          updatedAt: "2026-05-27T00:00:00.000Z",
        },
      },
      events: [],
    },
  },
  ledgers: {},
  leases: { leases: {} },
  contracts: {},
}

describe("runesmith cli", () => {
  test("init writes a project config", async () => {
    const host = createMemoryHost()

    const result = await runCli(["init"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: "Created .runesmith/config.json\n",
      stderr: "",
    })
    expect(host.readText(".runesmith/config.json")).toBe(JSON.stringify({
      version: 1,
      runtimeDir: ".runesmith/runtime",
      defaultStaleAfterMs: 120000,
    }, null, 2))
  })

  test("doctor fails with actionable readiness checks when install files are missing", async () => {
    const host = createMemoryHost({
      ".runesmith/config.json": "{}",
    })

    const result = await runCli(["doctor", "--plugin-dir", ".opencode/plugins"], host)

    expect(result).toEqual({
      exitCode: 1,
      stdout: [
        "Runesmith doctor",
        "config: found (.runesmith/config.json)",
        "runtime capsule: missing (.runesmith/runtime/capsule.json)",
        "opencode plugin: missing (.opencode/plugins/runesmith.ts)",
        "loop smoke: passed (mission completed)",
        "status: incomplete",
        "next: run `runesmith up` to initialize config, runtime, and OpenCode plugin wiring.",
        "",
      ].join("\n"),
      stderr: "",
    })
  })

  test("doctor reports ready after up installs the runtime and OpenCode shim", async () => {
    const host = createMemoryHost()

    const up = await runCli([
      "up",
      "--plugin-dir",
      ".opencode/plugins",
      "--source",
      "E:/dev/Oh-my/runesmith/packages/opencode-adapter/src/plugin.ts",
    ], host)
    expect(up.exitCode).toBe(0)

    const result = await runCli(["doctor", "--plugin-dir", ".opencode/plugins"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Runesmith doctor",
        "config: found (.runesmith/config.json)",
        "runtime capsule: valid (.runesmith/runtime/capsule.json)",
        "opencode plugin: found (.opencode/plugins/runesmith.ts)",
        "loop smoke: passed (mission completed)",
        "status: ready",
        "",
      ].join("\n"),
      stderr: "",
    })
  })

  test("doctor validates npm-mode OpenCode plugin config", async () => {
    const host = createMemoryHost()

    const up = await runCli([
      "up",
      "--mode",
      "npm",
      "--config",
      "opencode.jsonc",
      "--package",
      "runesmith@0.2.0",
    ], host)
    expect(up.exitCode).toBe(0)

    const result = await runCli(["doctor", "--mode", "npm", "--config", "opencode.jsonc"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Runesmith doctor",
        "config: found (.runesmith/config.json)",
        "runtime capsule: valid (.runesmith/runtime/capsule.json)",
        "opencode plugin: found (opencode.jsonc)",
        "loop smoke: passed (mission completed)",
        "status: ready",
        "",
      ].join("\n"),
      stderr: "",
    })
  })

  test("install writes a local OpenCode plugin shim", async () => {
    const host = createMemoryHost()

    const result = await runCli([
      "install",
      "--plugin-dir",
      ".opencode/plugins",
      "--source",
      "E:/dev/Oh-my/runesmith/packages/opencode-adapter/src/plugin.ts",
    ], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Installed Runesmith local plugin",
        "plugin: .opencode/plugins/runesmith.ts",
        "source: file:///E:/dev/Oh-my/runesmith/packages/opencode-adapter/src/plugin.ts",
        "covenant: automatic",
        "",
      ].join("\n"),
      stderr: "",
    })
    expect(host.readText(".opencode/plugins/runesmith.ts")).toBe([
      "// Generated by Runesmith. Re-run `runesmith install` to refresh.",
      "export { default } from \"file:///E:/dev/Oh-my/runesmith/packages/opencode-adapter/src/plugin.ts\"",
      "",
    ].join("\n"))
  })

  test("install can add an npm plugin entry to opencode config without duplicates", async () => {
    const host = createMemoryHost({
      "opencode.jsonc": "{\n  // keep my plugin\n  \"plugin\": [\"existing-plugin\", \"runesmith@0.1.0\"]\n}\n",
    })

    const result = await runCli([
      "install",
      "--mode",
      "npm",
      "--config",
      "opencode.jsonc",
      "--package",
      "runesmith@0.2.0",
    ], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Installed Runesmith npm plugin",
        "config: opencode.jsonc",
        "plugin: runesmith@0.2.0",
        "backup: opencode.jsonc.runesmith.bak",
        "covenant: automatic",
        "",
      ].join("\n"),
      stderr: "",
    })
    expect(host.readText("opencode.jsonc")).toContain("\"existing-plugin\"")
    expect(host.readText("opencode.jsonc")).toContain("\"runesmith@0.2.0\"")
    expect(host.readText("opencode.jsonc")).not.toContain("\"runesmith@0.1.0\"")
    expect(host.readText("opencode.jsonc.runesmith.bak")).toContain("\"runesmith@0.1.0\"")
  })

  test("up initializes the workspace, installs OpenCode, and creates the runtime capsule", async () => {
    const host = createMemoryHost()

    const result = await runCli([
      "up",
      "--plugin-dir",
      ".opencode/plugins",
      "--source",
      "E:/dev/Oh-my/runesmith/packages/opencode-adapter/src/plugin.ts",
    ], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Runesmith OS is ready",
        "config: .runesmith/config.json",
        "plugin: .opencode/plugins/runesmith.ts",
        "runtime: .runesmith/runtime/capsule.json",
        "covenant: automatic",
        "dashboard: bun run dev:dashboard",
        "",
      ].join("\n"),
      stderr: "",
    })
    expect(host.readText(".runesmith/config.json")).toContain("\"runtimeDir\": \".runesmith/runtime\"")
    expect(host.readText(".opencode/plugins/runesmith.ts")).toContain("opencode-adapter/src/plugin.ts")

    const capsule = JSON.parse(host.readText(".runesmith/runtime/capsule.json"))
    expect(capsule).toMatchObject({
      version: 1,
      runtime: {
        graphs: {},
        ledgers: {},
        leases: { leases: {} },
        contracts: {},
      },
    })
    expect(typeof capsule.updatedAt).toBe("string")
  })

  test("mission list prints mission summaries from a snapshot", async () => {
    const host = createMemoryHost({
      "snapshot.json": JSON.stringify(snapshot),
    })

    const result = await runCli(["mission", "list", "--snapshot", "snapshot.json"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: "mission_alpha running Build Runesmith\n",
      stderr: "",
    })
  })

  test("mission list reads the default runtime capsule without a snapshot flag", async () => {
    const host = createMemoryHost({
      ".runesmith/runtime/capsule.json": JSON.stringify({
        version: 1,
        updatedAt: "2026-05-27T00:00:00.000Z",
        runtime: snapshot,
      }),
    })

    const result = await runCli(["mission", "list"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: "mission_alpha running Build Runesmith\n",
      stderr: "",
    })
  })

  test("mission inspect prints graph details from a snapshot", async () => {
    const host = createMemoryHost({
      "snapshot.json": JSON.stringify(snapshot),
    })

    const result = await runCli(["mission", "inspect", "mission_alpha", "--snapshot", "snapshot.json"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Mission mission_alpha",
        "Status: running",
        "Goal: Build Runesmith",
        "Tasks:",
        "- task_alpha running agent_atlas Mission root",
        "",
      ].join("\n"),
      stderr: "",
    })
  })

  test("mission inspect reads the default runtime capsule without a snapshot flag", async () => {
    const host = createMemoryHost({
      ".runesmith/runtime/capsule.json": JSON.stringify({
        version: 1,
        updatedAt: "2026-05-27T00:00:00.000Z",
        runtime: snapshot,
      }),
    })

    const result = await runCli(["mission", "inspect", "mission_alpha"], host)

    expect(result).toEqual({
      exitCode: 0,
      stdout: [
        "Mission mission_alpha",
        "Status: running",
        "Goal: Build Runesmith",
        "Tasks:",
        "- task_alpha running agent_atlas Mission root",
        "",
      ].join("\n"),
      stderr: "",
    })
  })
})
